### ISSUE TITLE
Edit the bounce-tracking explainer to align it with being a Privacy CG work item.

### ISSUE THREAD

**Issue by jyasskin** [privacycg/nav-tracking-mitigations#30]
@pes10k mentions that it shouldn't mention FPS anymore, but please also check for any other awkward bits.

**Comment by wanderview** [comment]
In regards to FPS, I originally added that text because I guessed that some folks would assume that the bounce tracking mitigations would integrate with FPS.  I think we have some evidence that this is the case as well based on issue #26.

In regard to the "other awkward bits", can you clarify what you mean?  I seem to recall voicing the explainer as coming from chromium, but I wonder if you have specific things you can point to.

**Comment by jyasskin** [comment]
There are fewer awkward bits than I expected. I think I overindexed on the first one of these since it appeared early in the document:
* "These are summarized in a PrivacyCG [draft report](https://privacycg.github.io/nav-tracking-mitigations/#deployed-mitigations)."
* The [first-party sets](https://github.com/privacycg/first-party-sets) link points to the old location of that repository. I actually disagree with @pes10k and think this section fits well here, since it's in the "considered alternatives" section.
* "It is not new information because this kind of data can be tracked and shared today." isn't quite the style of rationale the Privacy CG likes to use. I suspect this particular tracker->site communication is ok because if we do nothing about bounce tracking, that piece of information is even easier to send.
* Is there anything new to replace "Pending feedback after publication." with?
* "A description of these features are summarized in a PrivacyCG [draft report](https://privacycg.github.io/nav-tracking-mitigations/#deployed-mitigations)." and "In addition we are thankful for the work being done in the [PrivacyCG](https://privacycg.github.io/nav-tracking-mitigations/) on this topic." both have an outside-the-CG voice.

**Comment by wanderview** [comment]
Thanks.  I'll try to send a PR to fix these this week.
